### PR TITLE
Improve changelog

### PR DESCRIPTION
**Pull request by Rlamboll**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/GranthamImperial/silicone/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/GranthamImperial/silicone/pull/XX>`_) Fixed bug identified in (`#YY <https://github.com/GranthamImperial/silicone/issues/YY>`_)
```

### CODE REVIEW

**Review by znicholls — COMMENTED** [review]
Nice, is there a reason you don't want to copy the format and headings from https://keepachangelog.com/en/1.0.0/ exactly? If nothing else, adding the underlines means the restructured text will render as headings.

**Comment by Rlamboll** [comment]
We can certainly add underlines if that's helpful. I didn't really see the point of having so many subsections for each version when we are releasing patches every one or two updates, but we can do if you want them.

**Comment by znicholls** [comment]
I completely understand that having so many sub-sections can look stupid. My issue is, I don't know how to read the CHANGELOG as it is currently formatted. I don't really know what 'important update' means and it's not obvious where to look if I want to see how my code is affected by the changes. If we just copy the keep a changelog format, yes it seems like overkill but it's easy for any users to read and it makes clear that the only things people really need to worry about (if all they want to know is, "Will my code still work?") are the fixed and changed sections.

**Comment by Rlamboll** [comment]
OK @znicholls, I have filed all the post-release changes as one of the required categories and got rid of the summary.

**Review by znicholls — APPROVED** [review]
Great

**Pull request merged**
