### PR TITLE
Speedup rms

### PR DESCRIPTION
**Pull request by Rlamboll**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/GranthamImperial/silicone/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/GranthamImperial/silicone/pull/XX>`_) Fixed bug identified in (`#YY <https://github.com/GranthamImperial/silicone/issues/YY>`_)
```

### CODE REVIEW

**Review by znicholls — APPROVED** [review]
lgtm, one more in #143 if you want to add

**Comment by jkikstra** [comment]
Hi both. 
This seems like a great step-change improvement.

I ran this using 3 WITCH scenarios as input (which report most main gases, but not any of the HFCs or PFCs).
I called climate_assessment.cli.harmonise_and_infill(), using an infiller databse that contains 1394 scenarios.
There is a really marked improvement, indicating that RMSClosest is already very usable with just this implementation, well done!

============ runtimes ============

QRW for all.
total: 1min15sec
infilling: 35-40 sec (reported 1.6 sec / iteration) 

RMSClosest for all.
total: (stopped after 15 mins)
infilling: (was estimated to go on for about 1 hour, (reported 163 sec / iteration)

New RMSClosest implementation (commit 3cfd519e66793049382a7983481e505d1aca2f1a).
total: 1min10 sec
infilling: ~45 sec ((reported 2.0 sec / iteration)


============ one more note ============
Please note that with this runnning, now the log is getting filled with "SettingWithCopyWarning"s, like:
```
2021-10-05 01:13:25 climate_assessment.infilling MainThread - INFO:  Infilling Emissions|PFC|C4F10
C:\Users\kikstra\Miniconda3\envs\final-cleaning\lib\site-packages\silicone\database_crunchers\rms_closest.py:198: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["model"] = model
C:\Users\kikstra\Miniconda3\envs\final-cleaning\lib\site-packages\silicone\database_crunchers\rms_closest.py:199: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp["scenario"] = scenario
```

**Review by jkikstra — APPROVED** [review]

**Comment by znicholls** [comment]
> ============ runtimes ============

Sick, big props @Rlamboll !

**Comment by znicholls** [comment]
> ============ runtimes ============

Great reporting @jkikstra

**Pull request merged**
