### PR TITLE
Completeness check

### PR DESCRIPTION
**Pull request by Rlamboll**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/GranthamImperial/silicone/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/GranthamImperial/silicone/pull/XX>`_) Fixed bug identified in (`#YY <https://github.com/GranthamImperial/silicone/issues/YY>`_)
```

### CODE REVIEW

**Comment by znicholls** [comment]
Any chance you can split this? Its hundreds of new lines at the moment

**Comment by Rlamboll** [comment]
If you do #108  first it will be a lot shorter.

**Comment by znicholls** [comment]
> If you do #108 first it will be a lot shorter.

ah right I lost track my bad

**Comment by Rlamboll** [comment]
@znicholls or @jkikstra do either of you have time to review this?

**Review by znicholls — APPROVED** [review]
Wouldn't call it the world's most thorough review but looks pretty good to me!

**Comment by znicholls** [comment]
Just as an fyi, because `only_consistent_cases` is by default `True`, this is a backwards incompatible change. I think it's the right call, just wanted to double check it's on purpose?

**Comment by Rlamboll** [comment]
OK, it lets me get on with other things! Yes, fortunately we haven't finalised the version number yet and I think it's the better default.

**Pull request merged**
