### PR TITLE
Funders

### PR DESCRIPTION
**Pull request by Rlamboll**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added
- [x] Documentation added (where applicable)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/znicholls/silicone/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/znicholls/silicone/pull/XX>`_) Fixed bug identified in (`#YY <https://github.com/znicholls/silicone/issues/YY>`_)
```

### CODE REVIEW

**Comment by Rlamboll** [comment]
Hopefully the last PR for this version... add your own funding body if needed and thanks for your work!

**Review by znicholls — COMMENTED** [review]
I've never seen funding in a README before but can definitely include if you want (normally it just goes in the paper as that's what's indexed and actually 'counts' as far as I understand..). Maybe we should make a specific section in the README, e.g.

```
Funders
--------

Development of v1.0.0 of this project has received funding from the European Union’s Horizon 2020 research and
innovation programme under grant agreement No 820829.

# further finding info from later versions can go here
```

Can you put `scripts/test_install.py` back please, I'll use it in #93.

**Comment by Rlamboll** [comment]
> I've never seen funding in a README before but can definitely include if you want (normally it just goes in the paper as that's what's indexed and actually 'counts' as far as I understand..). Maybe we should make a specific section in the README, e.g.
> 
> ```
> Funders
> --------
> 
> Development of v1.0.0 of this project has received funding from the European Union’s Horizon 2020 research and
> innovation programme under grant agreement No 820829.
> 
> # further finding info from later versions can go here
> ```
> 
> Can you put `scripts/test_install.py` back please, I'll use it in #93.

The EU seem super-keen on being mentioned in databases too and so I assume it's better safe than sorry. You can have it back. I assume there is a clever way of making versioneer set a version to a given string, rather than me writing the string out?

**Review by znicholls — APPROVED** [review]
lgtm @Rlamboll 

Once this is merged, do you want to try making a release? Should be as easy as 

```
git checkout master
git pull
git tag v0.1.0rc1  # rc1 means release candidate 1, it's a way of indicating that this is probably v0.1.0 without fully committing (in case we decide to tweak something in the coming weeks)
git push
git push --tags
```

**Pull request merged**
