### PR TITLE
Improve release docs

### PR DESCRIPTION
**Pull request by znicholls**
# Pull request

Please confirm that this pull request has done the following:

- [x] #93 
- [x] Tests added (N/A)
- [x] Documentation added (where applicable)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable)
- [x] Description in ``CHANGELOG.rst`` added

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/znicholls/silicone/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/znicholls/silicone/pull/XX>`_) Fixed bug identified in (`#YY <https://github.com/znicholls/silicone/issues/YY>`_)
```

### CODE REVIEW

**Comment by znicholls** [comment]
Questions for @Rlamboll and @jkikstra on top of general review:

- would a link to an explanation of how semantic versioning works be useful?
- would a link to an explanation of how versioneer works be useful (e.g. 0.2.0 isn't a valid tag I don't think @Rlamboll)?
- do you want a stronger protocol for deciding when we make new versions (my opinion has always been that releases are basically free so it's not worth stressing about but others are much stricter e.g. pyam)?

You can see the CI-CD pipeline doing it's thing in the pipelines for the [v0.1.0rc tag](https://github.com/znicholls/silicone/actions/runs/96638670) and the [0.2.0 tag](https://github.com/znicholls/silicone/actions/runs/96638668).

**Review by Rlamboll — APPROVED** [review]
That is a lot simpler than before!

**Comment by Rlamboll** [comment]
> Questions for @Rlamboll and @jkikstra on top of general review:
> 
> * would a link to an explanation of how semantic versioning works be useful?
Not really, we can google it
> * would a link to an explanation of how versioneer works be useful (e.g. 0.2.0 isn't a valid tag I don't think @Rlamboll)?
Yes, I'm surprised that finding the documentation for how to use it (rather than what the codebase is) is so difficult. 
> * do you want a stronger protocol for deciding when we make new versions (my opinion has always been that releases are basically free so it's not worth stressing about but others are much stricter e.g. pyam)?
No, large version numbers are fine
> 
> You can see the CI-CD pipeline doing it's thing in the pipelines for the [v0.1.0rc tag](https://github.com/znicholls/silicone/actions/runs/96638670) and the [0.2.0 tag](https://github.com/znicholls/silicone/actions/runs/96638668).
Indeed, I apparently pip-installed it correctly (it ignores the 0.2.0 version).

**Comment by Rlamboll** [comment]
It doesn't actually pass the tests however, I get 
 from openscm_units.unit_registry import ScmUnitRegistry
E   ModuleNotFoundError: No module named 'openscm_units'

(I have openscm-units installed in this env and this persists even if I revert to openscm-units 0.1.1, which is what I was previously using.) Will have another look in the morning.

**Comment by znicholls** [comment]
> It doesn't actually pass the tests

As in `make test-pypi-install` doesn't work? Everything works on the CI servers from what I can tell.

**Comment by Rlamboll** [comment]
I wasn't running make because windows. I've tried it again and it works now, so I'm not sure what the problem was (I cleared the cache). Anyway, it seems to work for Joeri when installed everything from scratch, so presumably a problem connected to conda recovering old versions of files somehow?

**Comment by znicholls** [comment]
Ye weird, sometimes things don’t reinstall properly unless you start fresh..

**Comment by znicholls** [comment]
After #93 I think this is good to go too @Rlamboll

**Comment by Rlamboll** [comment]
OK @znicholls, I don't think Jarmo is going to review this so merge them at will

**Pull request merged**
