### PR TITLE
Turn on codecov upload

### PR DESCRIPTION
**Pull request by znicholls**
# Pull request

Please confirm that this pull request has done the following:

- [x] Tests added (N/A)
- [x] Documentation added (where applicable) (N/A)
- [x] Example added (either to an existing notebook or as a new notebook, where applicable) (N/A)
- [x] Description in ``CHANGELOG.rst`` added (N/A)

## Adding to CHANGELOG.rst

Please add a single line in the changelog notes similar to one of the following:

```
- (`#XX <https://github.com/GranthamImperial/silicone/pull/XX>`_) Added feature which does something
- (`#XX <https://github.com/GranthamImperial/silicone/pull/XX>`_) Fixed bug identified in (`#YY <https://github.com/GranthamImperial/silicone/issues/YY>`_)
```

### CODE REVIEW

**Comment by znicholls** [comment]
@Rlamboll I just sent a request to get codecov authorised for the GranthamImperial account

**Review by Rlamboll — APPROVED** [review]
Looks good!

**Comment by znicholls** [comment]
Hmm still not happy, we might need to turn on codecov in the repo settings (I'm not an admin but I think you just go setting, integrations then add codecov, maybe)

**Comment by znicholls** [comment]
Description here might help https://about.codecov.io/blog/how-to-set-up-codecov-with-c-and-github-actions/

**Pull request merged**
